# Generated by Django 2.0.13 on 2019-06-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_review_model_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='model_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='../reviewImages'),
        ),
    ]
