# Generated by Django 2.0.13 on 2019-06-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190601_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='model_pic',
            field=models.ImageField(upload_to='blog/static/images'),
        ),
    ]
