# Generated by Django 2.0.13 on 2019-06-01 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190601_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='model_pic',
            new_name='picture',
        ),
    ]
