# Generated by Django 2.0.13 on 2019-06-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190601_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='picture',
        ),
        migrations.AddField(
            model_name='review',
            name='url',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
