# Generated by Django 2.0.13 on 2019-06-01 16:36

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190601_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='description',
            field=froala_editor.fields.FroalaField(default='opis'),
        ),
    ]
