# Generated by Django 2.0.13 on 2019-06-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_review_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='description',
        ),
    ]
