# Generated by Django 2.0.13 on 2019-08-08 14:52

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_review_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='text',
            field=djrichtextfield.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=djrichtextfield.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=djrichtextfield.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
