# Generated by Django 2.0.13 on 2019-08-08 15:06

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190808_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
    ]
