# Generated by Django 2.0.13 on 2019-03-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
