# Generated by Django 2.0.13 on 2019-05-25 13:52

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190409_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='text',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
