# Generated by Django 2.0.13 on 2019-06-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190601_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='model_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='mysite/reviewImages/'),
        ),
    ]
